### ISSUE TITLE
Please stop it right now

### ISSUE THREAD

**Issue by henvic** [joaojeronimo/rimrafall#3]
We all know it's not safe and you've proved your point.

Please consider that people might install it not knowing the consequences and lose work. So, please, stop it right now.

Just comment the line or add a 'echo ' in front so that the command never runs and replace the package.

**Comment by henvic** [comment]
Or you can remove the rimrafall package directory itself or something that doesn't have the potential to mess up people's lives. Please consider this as a responsible disclosure advice.

**Comment by sarciszewski** [comment]
:-1: keep it up maybe we can actually educate some users the hard way!

**Comment by ErikPeterson** [comment]
@henvic anyone who would install a package without reading even a single line of its readme deserves what they get

**Comment by jgowdy** [comment]
The clown shoes are red and floppy.

**Comment by joaojeronimo** [comment]
I wanted it to be **solved** by npm, but all they did is [take it off npm](https://twitter.com/othiym23/status/559759478774439936). That and having an echo doesn't solve anything.
